### ISSUE TITLE
Build Failed!

### ISSUE THREAD

**Issue by WillianBR** [SoftwareAG/adabas-rest-webapp#29]
Does anything change on the Node Version?    I have followed all the steps carefully!

I'm just trying to build this guy to use with the [adabas-ce](https://hub.docker.com/r/softwareag/adabas-ce) and  [natural-ce](https://hub.docker.com/r/softwareag/natural-ce).

I'm reading the tutorial [Getting Started With Adabas & Natural Part 1](https://medium.com/@mohamad.razzi.my/getting-started-with-adabas-natural-part-1-6597688406ad).

```shell
C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp> npm run build

> adabas-operator@0.11.0 build
> vue-cli-service build


\  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
\  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
\  Building for production...C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\cache-loader\dist\index.js:147:7
    at C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:200:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1

C:\STUDIES\NATURAL_ADABAS\adabas-rest-webapp>
```

rev-parse:  `116a1f7e41b7d2dbb51d93f981dfe22955d5bd6d`
branch: `main`
Node.js `v18.17.1`
NPM `10.2.4`

Can anybody help me?

**Comment by PaulLCosareanu** [comment]
seems using Node v16.20.2 fixed it on my side
